# Generated by Django 5.1.4 on 2024-12-30 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('PROPIA', 'Cuenta Propia'), ('TERCEROS', 'Cuenta de Terceros')], max_length=10)),
                ('country', models.CharField(choices=[('PE', 'Perú'), ('BR', 'Brasil')], max_length=2, verbose_name='País de origen')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('swift_code', models.CharField(max_length=11)),
                ('bank_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['-created_at'],
            },
        ),
    ]
