# Generated by Django 5.1.4 on 2024-12-30 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payment_method', models.CharField(choices=[('interbank_soles', 'Interbank Soles'), ('bcp_soles', 'BCP Soles')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En Proceso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=20)),
                ('payment_voucher', models.FileField(blank=True, null=True, upload_to='vouchers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transactions', to='transactions.bankaccount')),
                ('destination_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_transactions', to='coin.currency')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_transactions', to='transactions.bankaccount')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transactions', to='coin.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
