# Generated by Django 5.1.4 on 2024-12-30 18:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('transactions', '0003_bankaccount_bank_name_bankaccount_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (example: WELCOME10)', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the coupon and its conditions')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the coupon becomes active')),
                ('end_date', models.DateTimeField(help_text='Date and time when the coupon expires')),
                ('max_uses', models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of times the coupon can be used. Null means unlimited', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times the coupon has been used')),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum transaction amount required to use the coupon', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the coupon is active or has been manually deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_currency', models.ForeignKey(help_text='Source currency for which the coupon applies', on_delete=django.db.models.deletion.PROTECT, related_name='source_coupons', to='coin.currency')),
                ('target_currency', models.ForeignKey(help_text='Target currency for which the coupon applies', on_delete=django.db.models.deletion.PROTECT, related_name='target_coupons', to='coin.currency')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
            },
        ),
    ]
