# Generated by Django 5.1.4 on 2025-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_address',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='swift_code',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_confirmation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmar Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cci_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número CCI'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cci_number_confirmation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmar Número CCI'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de DNI o CE'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='holder_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='holder_surnames',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Clave PIX'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='pix_key_confirmation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Confirmar clave PIX'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='pix_key_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de llave PIX'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=255, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(choices=[('BR', 'Brasil'), ('PE', 'Perú')], max_length=2, verbose_name='País'),
        ),
    ]
