# Generated by Django 5.1.4 on 2025-01-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_bankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Cuenta'),
        ),
    ]
