# Generated by Django 5.1.4 on 2025-02-03 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_voucher',
            field=models.FileField(blank=True, null=True, upload_to='admin_vouchers/', verbose_name='Admin Voucher Image'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.coupon'),
        ),
    ]
