# Generated by Django 5.1.4 on 2025-02-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_admin_voucher_transaction_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='third_party',
            field=models.BooleanField(default=False, verbose_name='Cuenta de terceros'),
        ),
    ]
