# Generated by Django 5.1.4 on 2025-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the coupon and its conditions', null=True),
        ),
    ]
