# Generated by Django 5.1.4 on 2025-02-19 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('transactions', '0010_alter_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Cuenta de Ahorro'), ('current', 'Cuenta Corriente')], max_length=10, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='coin.currency', verbose_name='Moneda'),
        ),
    ]
