# Generated by Django 5.1.4 on 2025-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_bankaccount_account_type_bankaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibido'), ('processing', 'En Proceso'), ('observed', 'Observado'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
