# Generated by Django 5.1.4 on 2025-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transaction_reason_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='legal_representative_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI o CE del Representante'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='legal_representative_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante Legal'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ruc_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de RUC'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('personal', 'Cuenta Personal'), ('business', 'Cuenta Empresa')], max_length=10, null=True, verbose_name='Tipo de Cuenta'),
        ),
    ]
