# Generated by Django 4.2.16 on 2025-04-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_bankaccount_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_send',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
