# Generated by Django 4.2.16 on 2025-04-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_transaction_commission_transaction_taxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cupon_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cupon_destination_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cupon_source_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cupon_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cupon_total_send',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
