# Generated by Django 4.2.16 on 2025-04-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transaction_cupon_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(max_length=150),
        ),
    ]
