# Generated by Django 4.2.16 on 2025-10-31 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image_cupon',
            field=models.ImageField(blank=True, help_text='Optional coupon image', null=True, upload_to='coupons/'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(blank=True, choices=[('automatic', 'automatic'), ('manual', 'manual')], help_text='Coupon application type: automatic or manual', max_length=10, null=True),
        ),
    ]
