# Generated by Django 4.2.16 on 2025-10-31 22:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('transactions', '0019_coupon_image_cupon_coupon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Unique coupon code (example: WELCOME10)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the coupon expires', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Indicates if the coupon is active or has been manually deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='source_currency',
            field=models.ForeignKey(blank=True, help_text='Source currency for which the coupon applies', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_coupons', to='coin.currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Date and time when the coupon becomes active', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='target_currency',
            field=models.ForeignKey(blank=True, help_text='Target currency for which the coupon applies', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_coupons', to='coin.currency'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of times the coupon has been used', null=True),
        ),
    ]
