# Generated by Django 4.2.16 on 2025-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_fill_missing_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='translations',
            field=models.JSONField(default=dict),
        ),
    ]
