# Generated by Django 4.2.16 on 2025-05-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='translations',
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('pt', 'Portugués')], default='es', max_length=2),
        ),
    ]
