# Generated by Django 5.1.4 on 2024-12-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+54', 'Argentina'), ('+55', 'Brasil'), ('+57', 'Colombia'), ('+591', 'Bolivia'), ('+51', 'Perú'), ('+56', 'Chile'), ('+58', 'Venezuela'), ('+598', 'Uruguay'), ('+595', 'Paraguay'), ('+1', 'Estados Unidos'), ('+351', 'Portugal'), ('+44', 'Inglaterra'), ('+34', 'España'), ('+593', 'Ecuador'), ('+52', 'México'), ('+507', 'Panamá'), ('+1', 'República Dominicana')], default=51, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_identity_document',
            field=models.CharField(blank=True, choices=[('DNI', 'Documento Nacional de Identidad'), ('CE', 'Carnet de Extranjería'), ('RG', 'Registro Geral'), ('CRNM', 'Carteira de Registro Nacional Migratório'), ('RNE', 'Registro Nacional de Extranjero'), ('PAS', 'Número de Pasaporte'), ('OTROS', 'Otros')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_situation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
