# Generated by Django 5.1.4 on 2025-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Soltero/a'), ('MARRIED', 'Casado/a'), ('DIVORCED', 'Divorciado/a')], max_length=50, null=True, verbose_name='Estado Civil'),
        ),
    ]
