# Generated by Django 5.1.4 on 2025-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('staff', 'Staff'), ('client', 'Client'), ('sales', 'sales')], default='client', max_length=50, unique=True, verbose_name='Role Name'),
        ),
    ]
