# Generated by Django 5.1.4 on 2025-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+51', 'Perú'), ('+54', 'Argentina'), ('(BRA)+55', 'Brasil'), ('(COL)+57', 'Colombia'), ('(BOL)+591', 'Bolivia'), ('(CHI)+56', 'Chile'), ('(VEN)+58', 'Venezuela'), ('(URU)+598', 'Uruguay'), ('(PAR)+595', 'Paraguay'), ('(USA)+1', 'Estados Unidos'), ('(PRT)+351', 'Portugal'), ('(ENG)+44', 'Inglaterra'), ('(ESP)+34', 'España'), ('(ECU)+593', 'Ecuador'), ('(MEX)+52', 'México'), ('(PAN)+507', 'Panamá'), ('(DOM)+1', 'República Dominicana')], max_length=50),
        ),
    ]
