# Generated by Django 5.1.4 on 2025-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+1', 'Estados Unidos'), ('+1', 'Canadá'), ('+52', 'México'), ('+55', 'Brasil'), ('+54', 'Argentina'), ('+57', 'Colombia'), ('+56', 'Chile'), ('+58', 'Venezuela'), ('+51', 'Perú'), ('+593', 'Ecuador'), ('+53', 'Cuba'), ('+591', 'Bolivia'), ('+506', 'Costa Rica'), ('+507', 'Panamá'), ('+598', 'Uruguay'), ('+34', 'España'), ('+49', 'Alemania'), ('+33', 'Francia'), ('+39', 'Italia'), ('+44', 'Reino Unido'), ('+7', 'Rusia'), ('+380', 'Ucrania'), ('+48', 'Polonia'), ('+40', 'Rumania'), ('+31', 'Países Bajos'), ('+32', 'Bélgica'), ('+30', 'Grecia'), ('+351', 'Portugal'), ('+46', 'Suecia'), ('+47', 'Noruega'), ('+86', 'China'), ('+91', 'India'), ('+81', 'Japón'), ('+82', 'Corea del Sur'), ('+62', 'Indonesia'), ('+90', 'Turquía'), ('+63', 'Filipinas'), ('+66', 'Tailandia'), ('+84', 'Vietnam'), ('+972', 'Israel'), ('+60', 'Malasia'), ('+65', 'Singapur'), ('+92', 'Pakistán'), ('+880', 'Bangladés'), ('+966', 'Arabia Saudita'), ('+20', 'Egipto'), ('+27', 'Sudáfrica'), ('+234', 'Nigeria'), ('+254', 'Kenia'), ('+212', 'Marruecos'), ('+213', 'Argelia'), ('+256', 'Uganda'), ('+233', 'Ghana'), ('+237', 'Camerún'), ('+225', 'Costa de Marfil'), ('+221', 'Senegal'), ('+255', 'Tanzania'), ('+249', 'Sudán'), ('+218', 'Libia'), ('+216', 'Túnez'), ('+61', 'Australia'), ('+64', 'Nueva Zelanda'), ('+679', 'Fiji'), ('+675', 'Papúa Nueva Guinea'), ('+676', 'Tonga'), ('+98', 'Irán'), ('+964', 'Iraq'), ('+962', 'Jordania'), ('+961', 'Líbano'), ('+965', 'Kuwait'), ('+971', 'Emiratos Árabes Unidos'), ('+968', 'Omán'), ('+974', 'Catar'), ('+973', 'Bahrein'), ('+967', 'Yemen'), ('+1', 'República Dominicana')], max_length=50),
        ),
    ]
