# Generated by Django 5.1.4 on 2025-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_identity_document',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI - Documento Nacional de Identidad'), ('CE', 'CE - Carnet de Extranjería'), ('RG', 'RG - Registro Geral'), ('CRNM', 'CRNM - Carteira de Registro Nacional Migratório'), ('RNE', 'RNE - Registro Nacional de Extranjero'), ('PAS', 'PAS - Número de Pasaporte'), ('OTROS', 'Otros')], max_length=50, null=True),
        ),
    ]
