# Generated by Django 4.2.16 on 2025-05-01 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_onetimepassword_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
