# Generated by Django 5.1.4 on 2025-02-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupimage',
            name='image',
        ),
        migrations.AddField(
            model_name='popupimage',
            name='image_br',
            field=models.FileField(blank=True, null=True, upload_to='popups/'),
        ),
        migrations.AddField(
            model_name='popupimage',
            name='image_pe',
            field=models.FileField(blank=True, null=True, upload_to='popups/'),
        ),
        migrations.AlterField(
            model_name='popupimage',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='popupimage',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='popupimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
