# Generated by Django 4.2.16 on 2025-05-19 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_popupimage_image_popupimage_image_br_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupimage',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the popup expires', null=True),
        ),
        migrations.AddField(
            model_name='popupimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the popup is active or has been manually deactivated'),
        ),
        migrations.AddField(
            model_name='popupimage',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the popup becomes active'),
        ),
    ]
