# Generated by Django 4.2.16 on 2025-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type_person', models.CharField(max_length=20)),
                ('ruc', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('type_identity_document', models.CharField(max_length=50)),
                ('identity_document_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('type_nonconformity', models.CharField(choices=[('claim', 'Claim'), ('complaint', 'Complaint')], max_length=10)),
                ('nonconformity_detail', models.TextField()),
                ('order_nonconformity', models.CharField(max_length=100)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
