# Generated by Django 4.2.16 on 2025-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='updated_by',
            field=models.CharField(default='', help_text='Usuario que realizó la última actualización', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
