# Generated by Django 4.2.16 on 2025-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_exchangerate_updated_by_exchangerate_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'get_latest_by': 'created_date', 'ordering': ['-created_date']},
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de comisión aplicado al intercambio de moneda', max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='reverse_commission',
            field=models.DecimalField(decimal_places=2, help_text='Comisión inversa para el intercambio de moneda en dirección opuesta', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_base_rates', to='coin.currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Tasa base→objetivo', max_digits=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='target_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_target_rates', to='coin.currency'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['base_currency', 'target_currency', 'range'], name='idx_comm_base_target_range'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['base_currency', 'created_date'], name='idx_base_created'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['target_currency', 'created_date'], name='idx_target_created'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency', 'range'), name='uniq_commission_triplet'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(('commission_percentage__gte', 0), ('commission_percentage__lte', 100)), name='commission_pct_0_100'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(check=models.Q(('reverse_commission__gte', 0), ('reverse_commission__lte', 100)), name='reverse_commission_0_100'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='uniq_base_target'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gt', 0)), name='rate_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('base_currency', models.F('target_currency')), _negated=True), name='base_ne_target'),
        ),
    ]
