# Generated by Django 4.2.16 on 2025-01-20 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='range',
            unique_together=set(),
        ),
    ]
